// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tifon.blog.classes;

import com.tifon.blog.classes.Publicacion;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Publicacion_Roo_Configurable {
    
    declare @type: Publicacion: @Configurable;
    
}
